Update adapterref.md
ioBroker/ioBroker.docs pull request #324
Opened 2021-08-23 15:06 UTC by paul53

Einige Korrekturen

2021-08-23 19:10 UTC, Apollon77 requested changes
Thank you ... wow auto translation is baaaad :-))

Please write "adaptername" in states and "object ID meaning" always lowercase to make sure devs understand that adapters can only have lowercase names

2021-08-23 19:10 UTC, Apollon77 commented on docs/de/dev/adapterref.md
> +Die ID des Objekts besteht aus verschiedenen Teilen. Jeder Teil wird durch "." von einander getrennt. Es gibt Systemobjekte (ID beginnt mit _ oder "system.") und Adapterobjekte (ID beginnt mit Adapte
```suggestion
Die ID des Objekts besteht aus verschiedenen Teilen. Jeder Teil wird durch "." von einander getrennt. Es gibt Systemobjekte (ID beginnt mit _ oder "system.") und Adapterobjekte (ID beginnt mit adaptername.instanznummer).
```

2021-08-23 19:10 UTC, Apollon77 commented on docs/de/dev/adapterref.md
> +Datenpunkte können in Kanälen und die Kanäle in Geräten gruppiert werden. Hier ist ein Beispiel für Homematic Geräte und Kanäle:
```suggestion
Objekte können in Kanälen und die Kanäle in Geräten gruppiert werden. Hier ist ein Beispiel für Homematic Geräte und Kanäle:
```

2021-08-23 19:10 UTC, Apollon77 commented on docs/de/dev/adapterref.md
> +Die Datenpunkt-ID muss immer mit der Kanal-ID und die Kanal-ID mit der Geräte-ID beginnen. Z.B. Im obigen Statusnamen hm-rpc.0.IEQ1234567.0.INFO ist der Teil hm-rpc.0.IEQ1234567.0 die Kanal-ID und hm
```suggestion
Die Objekt-ID muss immer mit der Kanal-ID und die Kanal-ID mit der Geräte-ID beginnen. Z.B. Im obigen Statusnamen hm-rpc.0.IEQ1234567.0.INFO ist der Teil hm-rpc.0.IEQ1234567.0 die Kanal-ID und hm-rpc.0.IEQ1234567 die Geräte-ID.
```

2021-08-23 19:10 UTC, Apollon77 commented on docs/de/dev/adapterref.md
> +Alle Objekt-IDs der Adapterinstanz beginnen mit Adaptername.X, wobei X die Nummer der Adapterinstanz ist.
```suggestion
Alle Objekt-IDs der Adapterinstanz beginnen mit adaptername.X, wobei X die Nummer der Adapterinstanz ist.
```

2021-08-23 19:10 UTC, Apollon77 commented on docs/de/dev/adapterref.md
> +* `system.adapter.Adaptername`: Beschreibung des Adapters (wie Name, Versionsnummer, ...)
```suggestion
* `system.adapter.adaptername`: Beschreibung des Adapters (wie Name, Versionsnummer, ...)
```

2021-08-23 19:10 UTC, Apollon77 commented on docs/de/dev/adapterref.md
> +* `Adaptername`: Objekt, das aus HTML/JS/CSS-Dateien des "www" Verzeichnisses des Adapters besteht. Dieses Objekt wird nur erstellt, wenn das Verzeichnis "www" im Adapterpaket gefunden wird.
```suggestion
* `adaptername`: Objekt, das aus HTML/JS/CSS-Dateien des "www" Verzeichnisses des Adapters besteht. Dieses Objekt wird nur erstellt, wenn das Verzeichnis "www" im Adapterpaket gefunden wird.
```

2021-08-23 19:10 UTC, Apollon77 commented on docs/de/dev/adapterref.md
> +* `Adaptername.admin`: Objekt, das aus HTML/JS/CSS-Dateien aus dem "admin" Verzeichnis des Adapterpakets besteht.
```suggestion
* `adaptername.admin`: Objekt, das aus HTML/JS/CSS-Dateien aus dem "admin" Verzeichnis des Adapterpakets besteht.
```

2021-08-23 19:10 UTC, Apollon77 commented on docs/de/dev/adapterref.md
> +* `main.js` - notwendig (kann auch `Adaptername.js` sein)
```suggestion
* `main.js` - notwendig (kann auch `adaptername.js` sein)
```

2021-08-23 19:10 UTC, Apollon77 commented on docs/de/dev/adapterref.md
> +* `xxx.png` - optional; besser: `Adaptername.png` (alle Bildformate werden unterstützt: jpeg, jpg, svg, bmp, ...)
```suggestion
* `xxx.png` - optional; besser: `adaptername.png` (alle Bildformate werden unterstützt: jpeg, jpg, svg, bmp, ...)
```

2021-08-23 19:10 UTC, Apollon77 commented on docs/de/dev/adapterref.md
> +* `system.adapter.Adaptername.X`: Konfiguration der Adapterinstanz
```suggestion
* `system.adapter.adaptername.X`: Konfiguration der Adapterinstanz
```

2021-08-23 19:10 UTC, Apollon77 commented on docs/de/dev/adapterref.md
> +* `system.adapter.Adaptername.X.alive`: Angabe, ob die Instanz aktiv ist (Nachrichten alle 30 Sekunden senden)
```suggestion
* `system.adapter.adaptername.X.alive`: Angabe, ob die Instanz aktiv ist (Nachrichten alle 30 Sekunden senden)
```

2021-08-23 19:10 UTC, Apollon77 commented on docs/de/dev/adapterref.md
> +* `system.adapter.Adaptername.X.connected`: Angabe, ob die Instanz mit dem Datenspeicher verbunden ist. Sie kann verbunden sein, aber aufgrund eines Deadlocks keine alive  Nachricht senden kann.
```suggestion
* `system.adapter.adaptername.X.connected`: Angabe, ob die Instanz mit dem Datenspeicher verbunden ist. Sie kann verbunden sein, aber aufgrund eines Deadlocks keine alive  Nachricht senden kann.
```

2021-08-23 19:10 UTC, Apollon77 commented on docs/de/dev/adapterref.md
> +* `system.adapter.Adaptername.X.memHeapTotal`: Speichernutzung Total
```suggestion
* `system.adapter.adaptername.X.memHeapTotal`: Speichernutzung Total
```

2021-08-23 19:10 UTC, Apollon77 commented on docs/de/dev/adapterref.md
> +* `system.adapter.Adaptername.X.memHeapUsed`: Speichernutzung
```suggestion
* `system.adapter.adaptername.X.memHeapUsed`: Speichernutzung
```

2021-08-23 19:10 UTC, Apollon77 commented on docs/de/dev/adapterref.md
> +* `system.adapter.Adaptername.X.memRss`: Speichernutzung
```suggestion
* `system.adapter.adaptername.X.memRss`: Speichernutzung
```

2021-08-23 19:10 UTC, Apollon77 commented on docs/de/dev/adapterref.md
> +* `system.adapter.Adaptername.X.uptime`: Sekunden die der Adapter läuft.
```suggestion
* `system.adapter.adaptername.X.uptime`: Sekunden die der Adapter läuft.
```

2021-08-23 19:10 UTC, Apollon77 commented on docs/de/dev/adapterref.md
> +* `states` - (nur Experten)
Lass uns das bitte löschen, ebenso nächste Zeile

2021-08-23 20:40 UTC, paul53 commented
adaptername (klein geschrieben) ist schlüssig.

2021-08-23 20:50 UTC, paul53 commented on docs/de/dev/adapterref.md
> +* `states` - (nur Experten)
Tu es.

2021-08-23 21:15 UTC, Apollon77 commented
lannst du bitte bei den ganzen vorschlägen "commit suggestion" klicken? :-)

2021-08-24 09:35 UTC, paul53 commented
Zur Liste der Funktionen: Es sollte angegeben werden, was an die Callback-Funktion übergeben wird.

2021-08-27 12:04 UTC, merged